### ISSUE TITLE
Session has been invlidated after running FBAL

### ISSUE THREAD

**Issue by ujeong1** [schmokel/FBAdLibrarian#1]
Hi,

I have run your program using "FBAL start", and it seems like my token for Facebook ad API has been invalidated. Is there any way to avoid it?

**Comment by schmokel** [comment]
Hi @ujeong1  

If it is a matter of an expired token you can refresh it on your FB API dashboard (https://developers.facebook.com/tools/explorer/) and run "FBAL start" again. There is a way to create a long-lived token with an expiration time of 60 days, but we haven't implemented it yet. (See https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing)

You are more than welcome to implement it under the class method get_longlived_token() in api.py and make a pull request (see the section "contribution" in the README)

**Comment by ujeong1** [comment]
Thanks for your reply. My point was that it seems like Facebook interrupts collecting image data using selenium. My token was valid until I run your program.

**Comment by mbossetta** [comment]
Hi @ujeong1 , 

I just regenerated tokens and it's working fine on a quick test run of ~100 images. Try regenerating your tokens and see if that fixes the issue.

**Comment by ujeong1** [comment]
Thanks for the reply. Just found that there is a problem on my side.
